version: 2

sources:
  - name: NYC_JOBS
    database: NYCAUDIT_DB
    schema: BRONZE    
    tables:
      - name: ANNUAL_PAYROLL
        description: "Annual payroll data for NYC jobs"
        columns:
          - name: "agency"
            description: "Agency name"
            tests:
              - not_null
          - name: "base_salary"
            description: "Minimum salary for the job"
            tests:
              - not_null
          - name: "pay_basis"
            description: "Basis of pay for the job"
            tests:
              - not_null


      - name: TOP_POSTED_TITLES
        description: "List of top job titles in postings"
        columns:
          - name: "Job Title"
            description: "Titles of Jobs"
            tests:
              - not_null
          - name: Unique Postings (Jan 2024 - Jun 2025)
            description: "Number of Postings"
            tests:
              - not_null

      - name: WEEKLY_JOBS
        description: "Weekly job postings data"
        columns:
          - name: "agency"
            description: "Agency name"
            tests:
              - not_null
          - name: "civil_service_title"
            description: "Standardized Job Title"
            tests:
              - not_null
          - name: "salary_frequency"
            description: "Frequency of salary payments"
            tests:
              - not_null

  - name: CLEANED_DATA
    database: NYCAUDIT_DB
    schema: SILVER
    tables:
      - name: CLEANED_PAYROLL
      - name: CLEANED_TOP_TITLES
      - name: CLEANED_WEEKLY_JOBS
